# Generated by Django 3.1.4 on 2020-12-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('publication_date', models.DateField()),
                ('image_url', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
