# Generated by Django 3.1.4 on 2020-12-11 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalcapstoneapi', '0002_resolutionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resolutionuser', to='finalcapstoneapi.resolutionuser'),
            preserve_default=False,
        ),
    ]
