# Generated by Django 3.1.4 on 2020-12-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalcapstoneapi', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='finalcapstoneapi.category'),
        ),
    ]
