# Generated by Django 3.1.4 on 2020-12-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalcapstoneapi', '0009_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
