# Generated by Django 3.1.4 on 2020-12-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalcapstoneapi', '0010_auto_20201229_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
